### ISSUE TITLE
Sb_leds.g

### ISSUE THREAD

**Issue by TechsavvyCNC** [Exerqtor/Voron#2]
When trying to use you led code on rrf 3.5 beta 3.  I keep getting a error for sb_led-state.g.  it say variable sb_led.g not found or no variable.

**Comment by Exerqtor** [comment]
Hmm maybe i forgot to push some changes 😬, I had to rework the macros a little due to changes in how neopixels are handeled from RRF 3.5b3 onwards. 

I atleast have a working version running on my machine (Duet 3 Mini / RRF 3.5b3++), so it's probably just a derp on my end! 

What board are you using btw?

**Comment by TechsavvyCNC** [comment]
Duet 3 6hc

**Comment by Exerqtor** [comment]
Ok, i just pushed the newest version of the macro set. Like i mention in the changelog on the readme you need to change the settings section of `sb_leds.g` to reflect on your printer.

**Comment by TechsavvyCNC** [comment]
Alright I'll give it a shot.  Do you have to copy the sb_leds-state and sb_leds-restore into sys/lib/led?

**Comment by TechsavvyCNC** [comment]
I keep getting this error  

Error: in file sb_leds-state.g line 8: unknown variable 'sb_leds'

**Comment by Exerqtor** [comment]
Ehm ok? Have you decleared the the `global.sb_leds` variable?

**Comment by TechsavvyCNC** [comment]
if var.sb_leds = global.sb_leds
  ; Same status, do nothing
else
  ; New status, change colors
  M98 P"/sys/lib/led/sb_leds.g"

**Comment by Exerqtor** [comment]
Type `global sb_leds = "ready" ` in console.

The whole "system" revolves around the global variable sb_leds. So you have to declare that on each startup. And to change colors you change the the variable value. For instance add `global sb_leds = "boot" ` at the bottom of your `config.g`.

And then you deploy `set global.sb_leds = "ready" ` (for instance) to "activate" the ready color combinations according to how they are configured to be inside of `sb_leds.g`.

If that makes any sense?

**Comment by TechsavvyCNC** [comment]
if i type global sb_leds = "ready" in the console then the error message goes away and the leds turn white.  When i home the printer they turn green like 8 seconds after its homed.  I added global sb_leds = "boot" and now it works after restarting the printer its just slow to change colors.

**Comment by Exerqtor** [comment]
Ok glad to hear you got it working (even though it's slow). 

I haven't had time/prioritized to write a better guide in regards to declaring `global.sb_leds` in the readme so that's on me. I'll try to update it soon™!

Regarding the colors changing slowly, have you got a delay set in your `daemon.g` or any of your homing macro's ? Thats the only reason I can think of that might make it slow.
